services:
  glvd-postgres:
    build:
      dockerfile: tests/integration/postgres-image-for-tests/Containerfile
    hostname: glvd-postgres
    networks:
      - glvd-triage-IT
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glvd -d glvd"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s

  ingestion:
    build:
      dockerfile: tests/integration/Containerfile
    environment:
      PGHOST: glvd-postgres
      PGPORT: 5432
      PGDATABASE: glvd
      PGUSER: glvd
      PGPASSWORD: glvd
    networks:
      - glvd-triage-IT
    depends_on:
      glvd-postgres:
        condition: service_healthy
        restart: false

  assert:
    build:
      dockerfile: tests/integration/assert.Containerfile
    environment:
      PGHOST: glvd-postgres
      PGPORT: 5432
      PGDATABASE: glvd
      PGUSER: glvd
      PGPASSWORD: glvd
    networks:
      - glvd-triage-IT
    depends_on:
      ingestion:
        condition: service_completed_successfully
        restart: false

networks:
  glvd-triage-IT: {}
