FROM ghcr.io/gardenlinux/glvd-postgres:latest

RUN rm /docker-entrypoint-initdb.d/create-extension.sql

COPY tests/integration/postgres-image-for-tests/01-schema.sql /docker-entrypoint-initdb.d/01-schema.sql
COPY tests/integration/postgres-image-for-tests/02-sample-data.sql /docker-entrypoint-initdb.d/02-sample-data.sql
